name: Choirs of America
favicon: null
layout_spectrum: 0.91301
typography_spectrum: 0.53886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a56c3e'
    - '#000000'
    - '#d3ab94'
    - '#573105'
    - '#d70a29'
  brandStrength: 0.5792860370129347
  lightness: 0.6117720163892955
  saturation: 0.38382383808493614
  rhythmicContrast: 0.43533861986361444
purpose: []
